### ISSUE TITLE
Accessory Name is undefined

### ISSUE THREAD

**Issue by fblazevski** [grover/homebridge-dacp#3]
Hi, so I installed the plugin as per instructions and configured the config file as follows (after troubleshooting it's exactly as the readme):

```json 
{
    "platform" : "DACP",
    "devices" : [
        {
            "name" : "New Remote Control"
        }
    ]
}
```

I get the following error now (I tried adding a name under the "platform" as it seems plugins should have a "name" but that didn't fix it. Any ideas? The error seems to do with the variable this._accessories Maybe it's not reading the name? (Line 146:5)

![plugin_error](https://user-images.githubusercontent.com/3319605/33888381-fa2332fa-dfa0-11e7-8459-bf76d7f385c5.PNG)

**Comment by grover** [comment]
Sorry that's a bug. I'll fix that with 0.7.3 tonight.

**Comment by grover** [comment]
I just published 0.7.3, which should fix this issue.

**Comment by fblazevski** [comment]
Awesome it works now 👍

**Comment by badrabbit** [comment]
Tried the paring process but it always crashes like this:
`[2017-12-17 18:43:06] Loaded plugin: homebridge-applescript-file
[2017-12-17 18:43:06] Registering accessory 'homebridge-applescript-file.ApplescriptFile'
[2017-12-17 18:43:06] ---
[2017-12-17 18:43:06] Loaded plugin: homebridge-config-ui
[2017-12-17 18:43:06] Registering platform 'homebridge-config-ui.config'
[2017-12-17 18:43:06] ---
[2017-12-17 18:43:06] ====================
[2017-12-17 18:43:06] ERROR LOADING PLUGIN homebridge-dacp:
[2017-12-17 18:43:06] /usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpClient.js:22
  async login(options) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/src/DacpAccessory.js:6:20)
[2017-12-17 18:43:06] ====================
[2017-12-17 18:43:06] Loaded plugin: homebridge-delay-switch
[2017-12-17 18:43:06] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2017-12-17 18:43:06] ---
[2017-12-17 18:43:06] Loaded config.json with 5 accessories and 2 platforms.
[2017-12-17 18:43:06] ---
[2017-12-17 18:43:06] Loading 2 platforms...
[2017-12-17 18:43:06] [Config] Initializing config platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'DACP' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by badrabbit** [comment]
Also without adding the pairing part to the config, the DACP-plugin won't load:

![bildschirmfoto 2017-12-17 um 18 48 33](https://user-images.githubusercontent.com/78358/34082262-30fe0bf2-e35b-11e7-9bb4-5e87fff7cca7.png)

**Comment by grover** [comment]
Which node version are you on? Both issues are related and likely due to an old node version.

**Comment by badrabbit** [comment]
8.9.3
![bildschirmfoto 2017-12-17 um 22 09 26](https://user-images.githubusercontent.com/78358/34083840-090c856c-e377-11e7-9534-f4117efe30fe.png)

**Comment by grover** [comment]
That should be good enough. Could you post the configuration? (Strip private data out of it please.)

Which version of the plugin do you have installed?

**Comment by badrabbit** [comment]
homebridge-dacp 0.7.4

> {
>   "bridge": {
>     "name": "Homebridge",
>     "username": "XX:XX:XX:XX:XX:XX",
>     "port": 51826,
>     "pin": "XXX-XX-XXX",
>     "manufacturer": "@nfarina",
>     "model": "Homebridge",
>     "serialNumber": "0.4.20"
>   },
>   "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
>   "accessories": [{
>       "accessory": "DelaySwitch",
>       "delay": 5000,
>       "name": "Delay5"
>     },
>     {
>       "accessory": "DelaySwitch",
>       "delay": 10000,
>       "name": "Delay10"
>     },
>     {
>       "accessory": "DelaySwitch",
>       "delay": 15000,
>       "name": "Delay15"
>     },
>     {
>       "accessory": "DelaySwitch",
>       "delay": 300000,
>       "name": "Delay30"
>     },
>     {
>       "accessory": "ApplescriptFile",
>       "on": "/Users/macmini_home/Documents/SCRIPTS/_Homebridge_Scripts/Projektor_ON.scpt",
>       "off": "/Users/macmini_home/Documents/SCRIPTS/_Homebridge_Scripts/Projektor_OFF.scpt",
>       "name": "Projektor"
>     }
>   ],
>   "platforms": [{
>       "platform": "config",
>       "port": 8088,
>       "log": "/var/log/homebridge.stdout.log",
>       "error_log": "/var/log/homebridge.stderr.log",
>       "restart": "/usr/local/bin/supervisorctl restart homebridge",
>       "name": "Config"
>     },
>     {
>     "platform": "DACP",
>     "devices": [
>       {
>         "name": "New Remote Control"
>       }
>     ]
>   }
>     
> 
>   ]
> }

**Comment by grover** [comment]
Hmm. This is curious - the same configuration works for me. I'm using:

- Node 8.3.0
- Homebridge 0.4.33
- homebridge-dacp 0.7.4

Do you maybe have multiple node versions installed? A different homebridge version?

**Comment by badrabbit** [comment]
Yap. That's it! Deleted and uninstalled all node stuff and reinstalled node and Homebridge. No more errors and the initial pairing process is up and running. Thanks for the help! :-)
