### ISSUE TITLE
Specific error: Error: Could not resolve Apple-TV.local when using gets

### ISSUE THREAD

**Issue by ptrvg** [grover/homebridge-dacp#41]
Hi,

I am just starting out with Homebridge. When I use a dns service for faking my location on the Apple TV  I get this error.

I use an Apple TV 4. The DACP Remote is successfully paired with Apple TV. And with dns set to automatic on the Apple TV it works ok.
I am using Raspberry Pi, Apple TV both connected wired to the local network.
Node js 8.94, bpm 5.6.0, Homebridge 0.4.38.

Is there a way to get it working with the getflix dns service enabled?

UPDATE: I got it working by editing the _onServiceUp method in DacpBrowser.js and setting  service.host there to the ipadress of my Apple TV. Still it would even be better if it could work without modding the code.

Thanks for a great plugin,

Peter

[2018-4-12 14:15:07] [DACP] Specific error: Error: Could not resolve Apple-TV.local - Query Timed Out
[2018-4-12 14:15:07] [DACP] Failed to resolve service Apple-TV.local. using IPv4 MDNS lookups.
    at Timer.listOnTimeout (timers.js:270:5)
    at tryOnTimeout (timers.js:310:5)
    at ontimeout (timers.js:475:11)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-dacp/node_modules/mdns-resolver/dist/index.js:14:18)
[2018-4-12 14:15:07] [DACP] Specific error: Error: Could not resolve Apple-TV.local - Query Timed Out
[2018-4-12 14:15:07] [DACP] Failed to resolve service Apple-TV.local. using IPv4 MDNS lookups.
[2018-4-12 14:15:05] [Living Room Apple TV] Opened connection to Living Room Apple TV
[2018-4-12 14:15:04] Homebridge is running on port 51826.
[2018-4-12 14:15:04] [DACP] Starting DACP browser...

**Comment by bohtho** [comment]
Mine also times out with similar error as above whatever DNS I have on my Apple TV.

**Comment by grover** [comment]
I have no control over the timeout in that spot. You can run multiple independent homebridge installs on the same machine if the number of plugins is the issue in your case. I would recommend to strip down the configuration to determine this.

This plugin needs a working (m)DNS environment to function properly. Hard-coding addresses might work, but may not always work.

**Comment by bohtho** [comment]
I removed all other plugins and dacp plugin 0.9.2 just says "Starting DACP browser..." and nothing more in the logs.
