### ISSUE TITLE
Error when adding iTunes Device

### ISSUE THREAD

**Issue by shaneakus** [grover/homebridge-dacp#42]
Hello,
I'm running homebridge on mac. I've got 3 separate apple TV's running no problem, but any time i add the device for iTunes and get the following error:

For testing purposes i launched SUDO homebridge

`[2018-4-26 11:56:29] [DACP] Starting DACP browser...

/usr/local/lib/node_modules/homebridge-dacp/src/index.js:79
      const artwork = device.features['album-artwork'];
                                     ^
TypeError: Cannot read property 'album-artwork' of undefined
    at config.devices.forEach.device (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:79:38)
    at Array.forEach (<anonymous>)
    at DacpPlatform._enableArtworkCameras (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:78:25)
    at DacpPlatform._didFinishLaunching (/usr/local/lib/node_modules/homebridge-dacp/src/index.js:72:10)
    at API.emit (events.js:185:15)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)`

Here's my config:

 "platforms": [
        {
            "platform": "HarmonyHub",
            "name": "Living Room Harmony Hub"
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": false
        },
        {
            "platform": "DACP",
            "devices": [
                {
                    "name": "AppleTV-Living Room",
                    "pairing": "REDACTED",
                    "serviceName": "REDACTED",
                    "features": {
                        "no-volume-controls": true
                    }
                },
                {
                    "name": "AppleTV-Bedroom",
                    "pairing": "REDACTED",
                    "serviceName": "REDACTED",
                    "features": {
                        "no-volume-controls": true
                    }
                },
                {
                    "name": "AppleTV-Kitchen",
                    "pairing": "REDACTED",
                    "serviceName": "REDACTED",
                    "features": {
                        "no-volume-controls": true
                    }
                },
                {
                    "name": "iTunes"
                }
            ]
        }
    ]
}

**Comment by grover** [comment]
This issue should be fixed with 0.9.2. If it doesn't work for you, please reopen this issue.

**Comment by 9SL9** [comment]
I have this issue, as well as others on 0.9.2
