### ISSUE TITLE
RangeError/Parsing Issue

### ISSUE THREAD

**Issue by fbthpg** [grover/homebridge-dacp#47]
Connects to iTunes and allows for Play/Pause functions through iOS Home only if alternate-playpause-switch is added as features.  Otherwise, shows as unsupported with no functionality.   Launches with errors:
`
error on mscu
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readIntBE (internal/buffer.js:330:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:927:26)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
error on aeSX
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readIntBE (internal/buffer.js:330:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:927:26)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
error on msma
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readIntBE (internal/buffer.js:330:3)
    at _decodeList (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:875:26)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:931:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:1157:10)
error on msma
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readIntBE (internal/buffer.js:330:3)
    at _decodeList (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:875:26)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:931:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:1157:10)
error on mper
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUIntBE (internal/buffer.js:162:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:929:26)
    at _decodeList (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:879:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:931:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'aeIM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4
error on mper
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUIntBE (internal/buffer.js:162:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:929:26)
    at _decodeList (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:879:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:931:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'meds' - don't know how to parse. length=4
error on mper
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readUIntBE (internal/buffer.js:162:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:929:26)
    at _decodeList (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:879:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:931:19)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
Skipping 'mdbk' - don't know how to parse. length=4
Skipping 'aeCs' - don't know how to parse. length=4
Skipping 'mrpr' - don't know how to parse. length=8
Skipping 'aeRM' - don't know how to parse. length=8
Skipping 'meds' - don't know how to parse. length=4
[6/15/2018, 5:16:49 PM] [DACP] Connected to [my] Library
error on asai
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:55:9)
    at Buffer.readIntBE (internal/buffer.js:330:3)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:927:26)
    at _decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:933:19)
    at Object.decode (/usr/local/lib/node_modules/homebridge-dacp/src/daap/Decoder.js:963:10)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpConnection.js:145:29)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-dacp/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
[6/15/2018, 5:16:49 PM] [DACP] Creating properties connection to 10.0.10.16:3689
[6/15/2018, 5:16:49 PM] [DACP] Updating characteristics with current volume: v=88
`

**Comment by fbthpg** [comment]
issue with my config.json - had multiple platforms in the same block.  plz close. thx
