### ISSUE TITLE
Fatal error while talking to Apple TV

### ISSUE THREAD

**Issue by sidharthb0** [grover/homebridge-dacp#51]
Hey Grover, 

Thanks for this plugin! I've seen some really great implementations made possible due to this and I'm finally getting the chance to try it out for myself. 

I followed the guide and got everything up as expected, until I restarted homebridge after adding the pairing and serviceName. I was hit with this error:

`[2018-9-15 20:22:30] [DACP] Connecting to AppleTV (192.168.1.177:3689)
[2018-9-15 20:22:30] [DACP] Creating status connection to 192.168.1.177:3689
Established connection to 192.168.1.177:3689 with session ID 1636090795
Skipping '' - don't know how to parse. length=0
Skipping '�=�' - don't know how to parse. length=1259258416
[2018-9-15 20:22:30] [DACP] Fatal error while talking to AppleTV:
[2018-9-15 20:22:30] [DACP]
[2018-9-15 20:22:30] [DACP]   Error: Error: Missing server info response container
    at _withConnection (/homebridge/node_modules/homebridge-dacp/src/dacp/DacpClient.js:33:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-9-15 20:22:30] [DACP]
[2018-9-15 20:22:30] [DACP] Attempting to reconnect to AppleTV in 204.8 seconds.
[2018-9-15 20:22:30] [DACP] [AppleTV] Connection to DACP server failed: Error: Missing server info response container
    at _withConnection (/homebridge/node_modules/homebridge-dacp/src/dacp/DacpClient.js:33:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8666) UnhandledPromiseRejectionWarning: IllegalStateError: Backoff in progress.
    at Backoff.backoff (/homebridge/node_modules/backoff/lib/backoff.js:38:13)
    at _dacpClient.connect.then.catch.error (/homebridge/node_modules/homebridge-dacp/src/DacpAccessory.js:243:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)`

Any idea what could be causing this? Side note: I'm using an Apple TV 2

Any help would be appreciated!

Cheers

**Comment by Binog** [comment]
I Do have this: 

`0|homebridge  | { IllegalStateError: Backoff in progress.
0|homebridge  |     at Backoff.backoff (/usr/local/lib/node_modules/homebridge-dacp/node_modules/backoff/lib/backoff.js:38:13)
0|homebridge  |     at _dacpClient.connect.then.catch.error (/usr/local/lib/node_modules/homebridge-dacp/src/DacpAccessory.js:243:23)
0|homebridge  |     at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Backoff in progress.' }`

any help?

**Comment by shaunhurley** [comment]
Did anyone get this working?  Seeing the same issue as above with an Apple TV 3rd Gen...
