### ISSUE TITLE
Error: TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by PaRkThEcAr** [grover/homebridge-dacp#67]
i seem to have this issue with my Apple TV. im running tvOS 12.4 and homebridge on macOS Mojave 10.4.6

`[8/23/2019, 4:27:57 PM] [DACP] Fatal error while talking to AppleTV:
[8/23/2019, 4:27:57 PM] [DACP] 
[8/23/2019, 4:27:57 PM] [DACP]   Error: TypeError: Cannot read property 'host' of undefined
    at DacpClient._withConnection (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpClient.js:229:67)
    at DacpClient.play (/usr/local/lib/node_modules/homebridge-dacp/src/dacp/DacpClient.js:175:23)
    at PlayerControlsService._setPlayState (/usr/local/lib/node_modules/homebridge-dacp/src/PlayerControlsService.js:46:24)
    at Characteristic.On.emit (events.js:209:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:209:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:209:13)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[8/23/2019, 4:27:57 PM] [DACP] 
[8/23/2019, 4:27:57 PM] [DACP] Failed to send the playback request to the device`

**Comment by PaRkThEcAr** [comment]
here is my Config file. 

`"name": "AppleTV",
                    "pairing": "NOPEYOUCANTSEEME",
                    "serviceName": "SAMEHERENOPEEKING",
                    "features": {
                        "no-volume-controls": true,
                        "alternate-playpause-switch": true`
