### ISSUE TITLE
install fails because of mdns on node v14.16.0

### ISSUE THREAD

**Issue by machineglow** [grover/homebridge-dacp#73]
Hi,  

I recently upgraded my node version (from v12 to v14) after upgrading my homebridge to 1.3.1 and I started getting errors loading the homebridge-dacp plugin because it was not compiled on the newer node version.

I uninstalled homebridge-dacp and tried reinstalling it but the install failed with the following error:

```
1678 info lifecycle detect-rpi@1.4.0~install: detect-rpi@1.4.0
1679 silly install mdns@2.7.2
1680 info lifecycle mdns@2.7.2~install: mdns@2.7.2
1681 verbose lifecycle mdns@2.7.2~install: unsafe-perm in lifecycle false
1682 verbose lifecycle mdns@2.7.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/homebridge-dacp/node_modules/mdns/node_modules/.bin:/usr/local/lib/node_modules/homebridge-dacp/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
1683 verbose lifecycle mdns@2.7.2~install: CWD: /usr/local/lib/node_modules/homebridge-dacp/node_modules/mdns
1684 silly lifecycle mdns@2.7.2~install: Args: [ '-c', 'node-gyp rebuild' ]
1685 silly lifecycle mdns@2.7.2~install: Returned: code: 1  signal: null
1686 info lifecycle mdns@2.7.2~install: Failed to exec install script
1687 timing action:install Completed in 352ms
1688 verbose unlock done using /home/myk/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
1689 timing stage:rollbackFailedOptional Completed in 209ms
1690 timing stage:runTopLevelLifecycles Completed in 3477ms
1691 verbose stack Error: mdns@2.7.2 install: `node-gyp rebuild`
1691 verbose stack Exit status 1
1691 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1691 verbose stack     at EventEmitter.emit (events.js:315:20)
1691 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1691 verbose stack     at ChildProcess.emit (events.js:315:20)
1691 verbose stack     at maybeClose (internal/child_process.js:1048:16)
1691 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
1692 verbose pkgid mdns@2.7.2
1693 verbose cwd /usr/local/lib/node_modules
1694 verbose Linux 4.13.0-46-generic
1695 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-dacp"
1696 verbose node v14.16.0
1697 verbose npm  v6.14.11
1698 error code ELIFECYCLE
1699 error errno 1
1700 error mdns@2.7.2 install: `node-gyp rebuild`
1700 error Exit status 1
1701 error Failed at the mdns@2.7.2 install script.
1701 error This is probably not a problem with npm. There is likely additional logging output above.
1702 verbose exit [ 1, true ]
```

Looks like the included node-gyp module fails.  Anyone encounter the same thing or know of a workaround?

Thanks,

**Comment by machineglow** [comment]
Not an issue anymore.  Decided to try reinstalling and setting up from command line and it worked this time. wierd.  maybe it's just not installable via config-ui-x
